//
//  flashCards.swift
//  flashCards
//
//  Created by misael rivera on 29/12/17.
//  Copyright © 2017 misael rivera. All rights reserved.
//

import Foundation

target "flashCards" do
pod "SAConfettiView"  
end

